### ISSUE TITLE
Pattern outdated

### ISSUE THREAD

**Issue by DasCanard** [sstokic-tgm/Gladiatorcheatz-v2#3]
A pattern has outtdated: 55 8B EC 83 7D 08 FF 56 8B F1 74 3D[Friday Jan  4 10:53:32 2019] dankme.mz repasted was successfully initialized!

How i can fix this?

**Comment by sstokic-tgm** [comment]
Use the right source though. Ask for dankme.mz creator, if you want up2date stuff, go on the v2.1 src.
